import type {
  Trainer,
  Call,
  RubricSection,
  Insight,
  Client,
  TrendPoint,
  GlobalMetrics,
} from '@/lib/types'

// ─── Trainers ────────────────────────────────────────────────────────────────

export const trainers: Trainer[] = [
  {
    id: 'trainer-marcus',
    name: 'Marcus R.',
    avatar: 'MR',
    avatarColor: 'blue',
    role: 'trainer',
    totalCalls: 28,
    closeRate: 74,
    closeDelta: 9,
    score: 91,
    lastActive: 'Ativo hoje',
    ownerId: 'owner-1',
    rubricScores: {
      discovery: 94,
      problemAgitation: 89,
      offerPresentation: 95,
      objectionHandling: 81,
      closeAndNextSteps: 90,
    },
  },
  {
    id: 'trainer-jamie',
    name: 'Jamie L.',
    avatar: 'JL',
    avatarColor: 'purple',
    role: 'trainer',
    totalCalls: 22,
    closeRate: 68,
    closeDelta: 4,
    score: 87,
    lastActive: 'Ontem',
    ownerId: 'owner-1',
    rubricScores: {
      discovery: 88,
      problemAgitation: 88,
      offerPresentation: 84,
      objectionHandling: 81,
      closeAndNextSteps: 82,
    },
  },
  {
    id: 'trainer-jordan',
    name: 'Jordan K.',
    avatar: 'JK',
    avatarColor: 'green',
    role: 'trainer',
    totalCalls: 19,
    closeRate: 61,
    closeDelta: 1,
    score: 79,
    lastActive: 'Ativo hoje',
    ownerId: 'owner-1',
    rubricScores: {
      discovery: 79,
      problemAgitation: 61,
      offerPresentation: 80,
      objectionHandling: 65,
      closeAndNextSteps: 65,
    },
  },
  {
    id: 'trainer-taylor',
    name: 'Taylor M.',
    avatar: 'TM',
    avatarColor: 'red',
    role: 'trainer',
    totalCalls: 14,
    closeRate: 55,
    closeDelta: -2,
    score: 74,
    lastActive: '3 dias atrás',
    ownerId: 'owner-1',
    rubricScores: {
      discovery: 67,
      problemAgitation: 58,
      offerPresentation: 70,
      objectionHandling: 55,
      closeAndNextSteps: 63,
    },
  },
]

// ─── Calls ───────────────────────────────────────────────────────────────────

export const calls: Call[] = [
  // Marcus R. — 7 calls, maioria fechadas
  {
    id: 'call-001',
    trainerId: 'trainer-marcus',
    trainerName: 'Marcus R.',
    date: '2026-03-22',
    duration: '38min',
    score: 94,
    result: 'closed',
    prospect: 'Bob W.',
    rubricScores: { discovery: 96, problemAgitation: 91, offerPresentation: 97, objectionHandling: 84, closeAndNextSteps: 92 },
    feedback: 'Excelente performance. Marcus demonstrou domínio completo do processo de discovery, fazendo 4 perguntas abertas antes de qualquer apresentação. O fechamento foi natural e sem pressão.',
    strengths: [
      'Fez 4 perguntas abertas antes de apresentar qualquer oferta',
      'Identificou a dor principal (Rex fugindo do quintal) em menos de 5 minutos',
      'Lidou com a objeção de preço usando ROI concreto: "quanto custa um cachorro perdido?"',
    ],
    improvements: [
      'Poderia ter aprofundado mais o problem agitation antes de passar para a oferta',
    ],
    transcript: 'Marcus: Oi Bob, obrigado por reservar um tempo hoje. Antes de qualquer coisa, me conta — o que está acontecendo com o Rex que fez você chegar até a gente?\nBob: Cara, ele simplesmente não obedece nada. A gente mal consegue sair de casa com ele.\nMarcus: Entendo. Quando você diz que ele não obedece — me dá um exemplo concreto que aconteceu recentemente?\nBob: Na semana passada ele fugiu do quintal pela terceira vez. A gente ficou duas horas procurando ele no bairro.\nMarcus: Nossa, que situação difícil. Isso deve ter dado um frio na barriga. E isso afeta o dia a dia de vocês além da questão da segurança?\nBob: Afeta demais. Minha filha tem medo de brincar com ele agora, e minha esposa já falou que se não resolver, vai ter que dar o cachorro.\nMarcus: Entendo a gravidade disso. Antes de mostrar o que a gente faz, me conta — vocês já tentaram alguma coisa antes? Aula em grupo, YouTube, algum adestrador?\n...',
  },
  {
    id: 'call-002',
    trainerId: 'trainer-marcus',
    trainerName: 'Marcus R.',
    date: '2026-03-20',
    duration: '42min',
    score: 91,
    result: 'closed',
    prospect: 'Sarah K.',
    rubricScores: { discovery: 95, problemAgitation: 88, offerPresentation: 94, objectionHandling: 80, closeAndNextSteps: 90 },
    feedback: 'Ótima call. Marcus usou o método de perguntas abertas com maestria. O momento de objeção foi bem tratado com redirecionamento para o valor da transformação.',
    strengths: [
      'Descobriu em 3 perguntas que o cachorro estava destruindo móveis por ansiedade de separação',
      'Apresentou a oferta como solução exata para a dor identificada',
      'Fechou sem desconto, mantendo o preço cheio',
    ],
    improvements: [
      'O problem agitation poderia ter sido mais específico com números e custos',
    ],
    transcript: 'Marcus: Sarah, me conta um pouco sobre o Thor. O que motivou você a entrar em contato hoje?\nSarah: Ele está destruindo tudo em casa quando a gente sai. Sofá, rodapé, até a porta ele arranhava...\nMarcus: Isso está acontecendo há quanto tempo?\nSarah: Desde que a gente voltou a trabalhar presencialmente, uns 4 meses mais ou menos.\n...',
  },
  {
    id: 'call-003',
    trainerId: 'trainer-marcus',
    trainerName: 'Marcus R.',
    date: '2026-03-18',
    duration: '35min',
    score: 89,
    result: 'closed',
    prospect: 'Mike D.',
    rubricScores: { discovery: 93, problemAgitation: 87, offerPresentation: 92, objectionHandling: 80, closeAndNextSteps: 88 },
    feedback: 'Call sólida. Discovery bem executado, oferta apresentada no momento certo. Pequena hesitação na objeção de tempo, mas contornada bem.',
    strengths: [
      'Descobriu que o problema real era vergonha na rua, não só comportamento em casa',
      'Usou prova social específica: "tivemos um Golden com o mesmo problema..."',
    ],
    improvements: [
      'Poderia ter parado mais tempo na fase de agitação antes de apresentar a solução',
    ],
    transcript: 'Marcus: Mike, o que está rolando com o Bolt?\nMike: Ele puxa a guia absurdamente. Ando torto de tanto segurar ele. Fico com vergonha de levar ele ao parque...\n...',
  },
  {
    id: 'call-004',
    trainerId: 'trainer-marcus',
    trainerName: 'Marcus R.',
    date: '2026-03-15',
    duration: '45min',
    score: 88,
    result: 'closed',
    prospect: 'Linda P.',
    rubricScores: { discovery: 92, problemAgitation: 86, offerPresentation: 91, objectionHandling: 79, closeAndNextSteps: 88 },
    feedback: 'Boa performance. Call mais longa que o normal, mas Marcus manteve o controle da conversa durante toda a duração.',
    strengths: [
      'Manteve o prospecto engajado durante 45 minutos com perguntas estratégicas',
      'Criou urgência real mencionando vagas limitadas no programa presencial',
    ],
    improvements: ['Next steps poderiam ser mais específicos — ficou sem data definida'],
    transcript: 'Marcus: Linda, a Bella está com quantos meses agora?\nLinda: Quase 8. E já é grande demais para a gente segurar quando fica agitada...\n...',
  },
  {
    id: 'call-005',
    trainerId: 'trainer-marcus',
    trainerName: 'Marcus R.',
    date: '2026-03-12',
    duration: '30min',
    score: 86,
    result: 'closed',
    prospect: 'Tom R.',
    rubricScores: { discovery: 91, problemAgitation: 84, offerPresentation: 89, objectionHandling: 78, closeAndNextSteps: 86 },
    feedback: 'Call eficiente e rápida. Marcus identificou que Tom já estava pronto para comprar desde o início e ajustou o ritmo corretamente.',
    strengths: [
      'Leu corretamente que o prospecto estava qualificado e acelerou a call',
      'Apresentou os planos em ordem crescente de valor',
    ],
    improvements: ['Discovery ficou um pouco curto — poderia ter extraído mais informação'],
    transcript: 'Marcus: Tom, antes de tudo — você já conhece o nosso método ou está chegando zerado?\nTom: Já pesquisei bastante. Vi os depoimentos no Instagram. Só quero saber como funciona na prática.\n...',
  },
  {
    id: 'call-006',
    trainerId: 'trainer-marcus',
    trainerName: 'Marcus R.',
    date: '2026-03-09',
    duration: '28min',
    score: 85,
    result: 'follow-up',
    prospect: 'Amy C.',
    rubricScores: { discovery: 93, problemAgitation: 88, offerPresentation: 90, objectionHandling: 76, closeAndNextSteps: 83 },
    feedback: 'Discovery e apresentação excelentes. A call não fechou porque Amy precisava confirmar disponibilidade de agenda com o marido — follow-up agendado para 2 dias.',
    strengths: [
      'Identificou a co-decisora (marido) antes de tentar fechar',
      'Deixou o follow-up com data e hora marcada, não aberto',
    ],
    improvements: ['Poderia ter sugerido incluir o marido na call em vez de adiar'],
    transcript: 'Marcus: Amy, me conta — quando você imagina o Duke completamente treinado, como você vê o dia a dia de vocês diferente?\nAmy: Seria incrível. A gente poderia levá-lo a qualquer lugar sem stress...\n...',
  },
  {
    id: 'call-007',
    trainerId: 'trainer-marcus',
    trainerName: 'Marcus R.',
    date: '2026-03-06',
    duration: '40min',
    score: 82,
    result: 'closed',
    prospect: 'Chris B.',
    rubricScores: { discovery: 90, problemAgitation: 85, offerPresentation: 88, objectionHandling: 72, closeAndNextSteps: 82 },
    feedback: 'Boa call com fechamento consistente. A objeção de preço surgiu de forma mais forte que o habitual e Marcus demorou um pouco para retomar o controle.',
    strengths: [
      'Manteve o tom calmo durante a objeção de preço mais resistente',
      'Usou a técnica do silêncio estratégico após a apresentação do preço',
    ],
    improvements: ['A resposta à objeção de preço poderia ter sido mais ágil e menos defensiva'],
    transcript: 'Marcus: Chris, no cenário atual sem o adestramento — quanto você acha que está "custando" o comportamento do Max?\nChris: Nunca parei para pensar assim...\nMarcus: O sofá que ele destruiu, as idas ao veterinário por estresse, a restrição de viajar com ele...\n...',
  },

  // Jamie L. — 5 calls
  {
    id: 'call-008',
    trainerId: 'trainer-jamie',
    trainerName: 'Jamie L.',
    date: '2026-03-21',
    duration: '35min',
    score: 90,
    result: 'closed',
    prospect: 'Diana M.',
    rubricScores: { discovery: 91, problemAgitation: 90, offerPresentation: 88, objectionHandling: 84, closeAndNextSteps: 87 },
    feedback: 'Excelente call de Jamie. O problem agitation foi particularmente forte — Diana ficou visualmente emocionada ao falar sobre o nível de estresse que o cão estava causando.',
    strengths: [
      'Problem agitation conduzido com empatia genuína — sem parecer manipulativo',
      'Fechamento feito antes da resistência surgir',
    ],
    improvements: ['Discovery poderia ter explorado mais o histórico de tentativas anteriores'],
    transcript: 'Jamie: Diana, o que acontece na sua casa quando vocês precisam receber visitas?\nDiana: É um caos. O Toby fica latindo e pulando em todo mundo. Já deixei de receber minha mãe por causa disso...\nJamie: Isso já durou quanto tempo?\nDiana: Mais de um ano. Estou exausta...\n...',
  },
  {
    id: 'call-009',
    trainerId: 'trainer-jamie',
    trainerName: 'Jamie L.',
    date: '2026-03-19',
    duration: '32min',
    score: 85,
    result: 'closed',
    prospect: 'Robert L.',
    rubricScores: { discovery: 88, problemAgitation: 86, offerPresentation: 84, objectionHandling: 80, closeAndNextSteps: 82 },
    feedback: 'Call bem conduzida e eficiente. Robert já tinha consciência do problema e Jamie soube calibrar a intensidade do agitation corretamente.',
    strengths: [
      'Calibrou corretamente o nível de agitation para um prospecto já consciente do problema',
      'Apresentou cases de raça similar (Border Collie)',
    ],
    improvements: ['O close poderia ter sido mais diretivo — ficou um pouco hesitante'],
    transcript: 'Jamie: Robert, quando você diz que o Luna "não foca" — descreve uma situação específica da última semana.\nRobert: Ontem mesmo. Tentei ensinar o "senta" por meia hora. Ela sabe fazer, mas ignora quando quer...\n...',
  },
  {
    id: 'call-010',
    trainerId: 'trainer-jamie',
    trainerName: 'Jamie L.',
    date: '2026-03-16',
    duration: '38min',
    score: 82,
    result: 'follow-up',
    prospect: 'Karen H.',
    rubricScores: { discovery: 87, problemAgitation: 85, offerPresentation: 82, objectionHandling: 78, closeAndNextSteps: 80 },
    feedback: 'Boa call. Karen é decisora compartilhada com o marido e Jamie identificou isso na metade da call — follow-up para inclui-lo.',
    strengths: [
      'Não tentou fechar sabendo que havia outro decisor na equação',
      'Manteve o engajamento de Karen para a próxima call',
    ],
    improvements: ['A questão do co-decisor poderia ter sido identificada mais cedo no discovery'],
    transcript: 'Jamie: Karen, o que te fez decidir buscar um adestrador profissional agora?\nKaren: Meu marido estava relutante, mas depois que o Buddy arranhon a criança, a gente concordou que precisava de ajuda...\n...',
  },
  {
    id: 'call-011',
    trainerId: 'trainer-jamie',
    trainerName: 'Jamie L.',
    date: '2026-03-13',
    duration: '25min',
    score: 79,
    result: 'closed',
    prospect: 'Steve N.',
    rubricScores: { discovery: 84, problemAgitation: 82, offerPresentation: 80, objectionHandling: 74, closeAndNextSteps: 78 },
    feedback: 'Call mais curta que o ideal. Jamie fechou mas deixou valor na mesa — Steve poderia ter comprado um plano mais completo com mais agitation.',
    strengths: ['Fechamento consistente mesmo em call mais curta', 'Tom direto e sem rodeios, adequado ao perfil do prospecto'],
    improvements: ['Problem agitation muito rápido — não explorou os custos emocionais do problema'],
    transcript: 'Jamie: Steve, quick question — o que mudaria na sua rotina se o Rocky obedecesse nos primeiros 3 meses?\nSteve: Principalmente as corridas. Ele tem potencial mas não foca...\n...',
  },
  {
    id: 'call-012',
    trainerId: 'trainer-jamie',
    trainerName: 'Jamie L.',
    date: '2026-03-10',
    duration: '42min',
    score: 75,
    result: 'no-close',
    prospect: 'Nancy W.',
    rubricScores: { discovery: 85, problemAgitation: 80, offerPresentation: 78, objectionHandling: 62, closeAndNextSteps: 70 },
    feedback: 'Discovery e agitation bem feitos, mas Jamie não conseguiu superar a objeção de preço de forma eficaz. Nancy saiu sem comprar e sem próximo passo claro.',
    strengths: ['Bom rapport construído na fase inicial', 'Discovery identificou a dor real corretamente'],
    improvements: [
      'Resposta à objeção de preço foi defensiva — entrou em modo de justificativa ao invés de reframing',
      'Não definiu próximo passo — call terminou sem compromisso',
    ],
    transcript: 'Nancy: O investimento está acima do que eu planejei gastar...\nJamie: Entendo, mas o nosso programa tem um excelente custo-benefício comparado a...\nNancy: Sim, mas no momento não tenho esse valor disponível...\n...',
  },

  // Jordan K. — 5 calls
  {
    id: 'call-013',
    trainerId: 'trainer-jordan',
    trainerName: 'Jordan K.',
    date: '2026-03-22',
    duration: '28min',
    score: 81,
    result: 'follow-up',
    prospect: 'Peter G.',
    rubricScores: { discovery: 82, problemAgitation: 65, offerPresentation: 83, objectionHandling: 70, closeAndNextSteps: 68 },
    feedback: 'Discovery razoável. Jordan identificou o problema mas passou muito rápido para a apresentação da oferta. Problem agitation ficou superficial.',
    strengths: ['Apresentação da oferta clara e bem estruturada', 'Tom confiante durante toda a call'],
    improvements: [
      'Pulou do discovery direto para a oferta sem agitar suficientemente o problema',
      'O follow-up ficou vago — "vou te mandar o material" sem data',
    ],
    transcript: 'Jordan: Peter, me conta o que está acontecendo com o Gobi.\nPeter: Ele é muito agitado. Pula em todo mundo, não para quieto.\nJordan: Entendi. Então, o que a gente oferece é um programa de 8 semanas...\n...',
  },
  {
    id: 'call-014',
    trainerId: 'trainer-jordan',
    trainerName: 'Jordan K.',
    date: '2026-03-19',
    duration: '35min',
    score: 75,
    result: 'closed',
    prospect: 'Donna F.',
    rubricScores: { discovery: 80, problemAgitation: 62, offerPresentation: 81, objectionHandling: 66, closeAndNextSteps: 65 },
    feedback: 'Fechou mas com desconto desnecessário. Jordan não criou valor suficiente na fase de agitation e cedeu no preço antes de explorar outras objeções.',
    strengths: ['Persistiu até fechar mesmo com objeção', 'Conhece bem o produto e apresentou com clareza'],
    improvements: [
      'Deu desconto sem tentar resolver a objeção de outras formas',
      'Problem agitation muito fraco — Donna não estava suficientemente comprometida',
    ],
    transcript: 'Jordan: Donna, vou ser direto — se você entrar hoje, consigo aplicar um desconto de 10%...\nDonna: Ah, assim fica melhor...\n...',
  },
  {
    id: 'call-015',
    trainerId: 'trainer-jordan',
    trainerName: 'Jordan K.',
    date: '2026-03-16',
    duration: '30min',
    score: 73,
    result: 'no-close',
    prospect: 'Mark T.',
    rubricScores: { discovery: 78, problemAgitation: 60, offerPresentation: 79, objectionHandling: 63, closeAndNextSteps: 62 },
    feedback: 'Call com bom início mas perdeu o fio condutor na metade. Jordan foi para a oferta muito cedo e não conseguiu reconquistar o engajamento do prospecto.',
    strengths: ['Abertura de call bem feita, criou boa atmosfera inicial'],
    improvements: [
      'Apresentou a oferta no minuto 10 — muito cedo, antes do problema estar bem estabelecido',
      'Não tentou recuperar quando sentiu que o prospecto estava desengajado',
    ],
    transcript: 'Jordan: Mark, muito prazer. Então, você está interessado em adestramento para o Rocky, certo?\nMark: É, vi no Google...\nJordan: Ótimo! Deixa eu te contar sobre o nosso programa...\n...',
  },
  {
    id: 'call-016',
    trainerId: 'trainer-jordan',
    trainerName: 'Jordan K.',
    date: '2026-03-13',
    duration: '25min',
    score: 70,
    result: 'follow-up',
    prospect: 'Susan B.',
    rubricScores: { discovery: 76, problemAgitation: 58, offerPresentation: 78, objectionHandling: 62, closeAndNextSteps: 60 },
    feedback: 'Call fraca. Jordan conseguiu apresentar o produto mas sem criar o contexto de urgência necessário para o fechamento.',
    strengths: ['Conhecimento do produto sólido'],
    improvements: [
      'Discovery muito superficial — 2 perguntas apenas antes de ir para a oferta',
      'Problem agitation praticamente inexistente',
      'Follow-up marcado mas sem qualificação real de interesse',
    ],
    transcript: 'Jordan: Susan, o Coco está com que problema?\nSusan: Ah, ele é meio agitado...\nJordan: Entendi. Quer que eu te mande mais informações sobre o programa?\n...',
  },
  {
    id: 'call-017',
    trainerId: 'trainer-jordan',
    trainerName: 'Jordan K.',
    date: '2026-03-10',
    duration: '20min',
    score: 65,
    result: 'no-close',
    prospect: 'James R.',
    rubricScores: { discovery: 68, problemAgitation: 55, offerPresentation: 72, objectionHandling: 60, closeAndNextSteps: 58 },
    feedback: 'Call muito curta e superficial. Jordan não conseguiu aprofundar a conversa o suficiente para criar valor.',
    strengths: ['Call pelo menos aconteceu — Jordan precisava de mais treino de discovery'],
    improvements: [
      'Call encerrada muito cedo — James precisava de mais tempo para confiar',
      'Nenhuma tentativa real de agitação do problema',
      'Fechamento prematuro sem base de valor',
    ],
    transcript: 'Jordan: James, me fala do Brutus.\nJames: Ele é grande demais para a gente controlar...\nJordan: Entendi. O nosso programa resolve isso. O investimento é X...\nJames: Hmm, vou pensar...\n...',
  },

  // Taylor M. — 4 calls
  {
    id: 'call-018',
    trainerId: 'trainer-taylor',
    trainerName: 'Taylor M.',
    date: '2026-03-20',
    duration: '22min',
    score: 74,
    result: 'no-close',
    prospect: 'Helen K.',
    rubricScores: { discovery: 70, problemAgitation: 60, offerPresentation: 74, objectionHandling: 58, closeAndNextSteps: 65 },
    feedback: 'Taylor demonstrou conhecimento do produto mas teve dificuldade em conectar o produto à dor real da Helen. A call foi técnica demais e emocional de menos.',
    strengths: ['Conhece bem as especificações e diferenciais do programa'],
    improvements: [
      'Discovery muito técnico — focou em comportamentos do cão, não nos impactos na vida da tutora',
      'Quando Helen hesitou, Taylor recuou em vez de avançar com empatia',
    ],
    transcript: 'Taylor: Helen, o Ziggy tem problemas com qual comando especificamente? Fica, senta, ou é mais agressividade?\nHelen: Ele é muito reativo com outros cães na rua...\nTaylor: Entendi. Reatividade é uma das nossas especialidades...\n...',
  },
  {
    id: 'call-019',
    trainerId: 'trainer-taylor',
    trainerName: 'Taylor M.',
    date: '2026-03-17',
    duration: '28min',
    score: 71,
    result: 'no-close',
    prospect: 'Paul M.',
    rubricScores: { discovery: 68, problemAgitation: 58, offerPresentation: 72, objectionHandling: 55, closeAndNextSteps: 62 },
    feedback: 'Segunda call consecutiva sem fechar. Taylor está com dificuldade clara na etapa de objeção — fica na defensiva em vez de manter o foco no valor.',
    strengths: ['Apresentação do programa estruturada e completa'],
    improvements: [
      'Objeção de preço: entrou em modo de justificativa imediata',
      'Problem agitation muito rápido — Paul não sentiu urgência real',
      'Não tentou incluir o próspecto na solução durante a call',
    ],
    transcript: 'Paul: Fica caro para o que é...\nTaylor: Entendo que o preço pode parecer alto, mas se você dividir por semana...\nPaul: Hmm...\nTaylor: Posso também te explicar o que inclui...\n...',
  },
  {
    id: 'call-020',
    trainerId: 'trainer-taylor',
    trainerName: 'Taylor M.',
    date: '2026-03-14',
    duration: '18min',
    score: 68,
    result: 'follow-up',
    prospect: 'Alice N.',
    rubricScores: { discovery: 65, problemAgitation: 57, offerPresentation: 71, objectionHandling: 53, closeAndNextSteps: 61 },
    feedback: 'Call muito curta. Taylor parece estar se sentindo inseguro — as perguntas do discovery foram tímidas e a apresentação da oferta foi muito rápida.',
    strengths: ['Marcou um follow-up — ao menos não deixou sem próximo passo'],
    improvements: [
      'Discovery com apenas 2 perguntas antes de ir para a oferta',
      'Tom inseguro na apresentação — Alice provavelmente não percebeu o valor real',
      'Call encerrada sem Taylor saber o verdadeiro motivo da hesitação',
    ],
    transcript: 'Taylor: Alice, o que te motivou a pesquisar adestramento?\nAlice: A Mel está mordendo um pouco as coisas em casa...\nTaylor: Entendi. Deixa eu te mandar as informações do programa por WhatsApp?\n...',
  },
  {
    id: 'call-021',
    trainerId: 'trainer-taylor',
    trainerName: 'Taylor M.',
    date: '2026-03-11',
    duration: '25min',
    score: 65,
    result: 'no-close',
    prospect: 'George T.',
    rubricScores: { discovery: 63, problemAgitation: 55, offerPresentation: 70, objectionHandling: 52, closeAndNextSteps: 60 },
    feedback: 'Call preocupante. Taylor está demonstrando sinais claros de baixa confiança. A voz estava hesitante e ele deixou o prospecto liderar a conversa inteira.',
    strengths: ['Conseguiu manter George na call por 25 minutos'],
    improvements: [
      'Deixou o prospecto conduzir a call — perdeu o controle da conversa',
      'Não fez nenhuma tentativa real de fechamento',
      'Encerrou a call com "vou pensar no que você disse" — posição passiva',
    ],
    transcript: 'George: Quanto custa?\nTaylor: O investimento é... depende do plano. Tem opções a partir de...\nGeorge: É, mas qual é o mais básico?\nTaylor: O básico inclui...\nGeorge: Hmm, deixa eu pensar...\nTaylor: Claro, sem problemas...\n...',
  },
]

// ─── Rubric Sections ─────────────────────────────────────────────────────────

export const rubricSections: RubricSection[] = [
  {
    id: 'discovery',
    name: 'Discovery',
    weight: 20,
    isCritical: true,
    description: 'Qualidade das perguntas abertas e escuta ativa. O vendedor deve identificar a dor real antes de qualquer apresentação.',
    teamAvg: 83,
    color: 'blue',
    trainerScores: { marcus: 94, jamie: 88, jordan: 79, taylor: 67 },
  },
  {
    id: 'problemAgitation',
    name: 'Problem Agitation',
    weight: 25,
    isCritical: true,
    description: 'Capacidade de aprofundar e expandir a dor do prospecto, conectando o problema a consequências emocionais e financeiras reais.',
    teamAvg: 72,
    color: 'amber',
    trainerScores: { marcus: 89, jamie: 88, jordan: 61, taylor: 58 },
  },
  {
    id: 'offerPresentation',
    name: 'Offer Presentation',
    weight: 20,
    isCritical: false,
    description: 'Clareza e impacto na apresentação da oferta. O produto deve ser apresentado como a solução exata para a dor identificada.',
    teamAvg: 86,
    color: 'green',
    trainerScores: { marcus: 95, jamie: 84, jordan: 80, taylor: 70 },
  },
  {
    id: 'objectionHandling',
    name: 'Objection Handling',
    weight: 25,
    isCritical: true,
    description: 'Manejo de objeções de preço, tempo e necessidade sem entrar em modo defensivo ou oferecer desconto prematuramente.',
    teamAvg: 64,
    color: 'red',
    trainerScores: { marcus: 81, jamie: 81, jordan: 65, taylor: 55 },
  },
  {
    id: 'closeAndNextSteps',
    name: 'Close & Next Steps',
    weight: 10,
    isCritical: true,
    description: 'Qualidade do fechamento e clareza nos próximos passos. Toda call deve terminar com um compromisso claro.',
    teamAvg: 78,
    color: 'accent2',
    trainerScores: { marcus: 90, jamie: 82, jordan: 65, taylor: 63 },
  },
]

// ─── Insights ─────────────────────────────────────────────────────────────────

export const insights: Insight[] = [
  {
    id: 'insight-1',
    type: 'risk',
    icon: '🚨',
    title: 'Objection Handling é o maior vazamento de receita',
    tag: 'Padrão de equipe',
    tagColor: 'red',
    summary:
      '3 de 4 trainers marcam abaixo de 70 em Objection Handling. Calls que pulam essa etapa fecham a 38% vs. 71% quando é executada corretamente.',
    action:
      'Role-play de 30min focado em objeções de preço. Usar calls de Marcus como benchmark.',
  },
  {
    id: 'insight-2',
    type: 'warning',
    icon: '⚠️',
    title: 'Taylor está em risco de desengajamento',
    tag: 'Alerta de trainer',
    tagColor: 'amber',
    summary:
      'Score caiu 12pts em 2 semanas, volume de calls caiu 40%, e close rate é o mais baixo com 55%. Emergência de coaching, não de performance.',
    action:
      'Agende um 1:1 com Taylor. Analise as últimas 3 calls e identifique onde a confiança caiu.',
  },
  {
    id: 'insight-3',
    type: 'tip',
    icon: '💡',
    title: 'Discovery de Marcus pode elevar toda a equipe',
    tag: 'Boas práticas',
    tagColor: 'blue',
    summary:
      'Marcus marca 94 em Discovery — 11pts acima da média. Ele faz 3 perguntas abertas antes de apresentar a oferta. Nenhum outro trainer replica isso.',
    action:
      'Extraia 2 clips das calls de Marcus e compartilhe como material de treinamento na próxima reunião.',
  },
  {
    id: 'insight-4',
    type: 'positive',
    icon: '📈',
    title: 'Coaching funcionando — close rate +7pts em 6 semanas',
    tag: 'Sinal de ROI',
    tagColor: 'green',
    summary:
      'Desde o início do coaching com IA, o close rate passou de 57% → 64%. Maior ganho em Offer Presentation (+12pts de média na equipe).',
    action:
      'Mantenha a cadência. Considere uploads diários para loops de feedback mais rápidos.',
  },
]

// ─── Clients (admin view) ────────────────────────────────────────────────────

export const clients: Client[] = [
  {
    id: 'client-1',
    name: 'Paw Masters Academy',
    plan: 'Pro',
    callsThisMonth: 83,
    avgScore: 83,
    mrr: 497,
    health: 'healthy',
    trainersCount: 4,
  },
  {
    id: 'client-2',
    name: 'Elite K9 Training',
    plan: 'Starter',
    callsThisMonth: 94,
    avgScore: 76,
    mrr: 297,
    health: 'at-risk',
    trainersCount: 6,
  },
  {
    id: 'client-3',
    name: 'Dog Whisperers Co.',
    plan: 'Pro+RAG',
    callsThisMonth: 70,
    avgScore: 88,
    mrr: 697,
    health: 'healthy',
    trainersCount: 3,
  },
]

export const globalMetrics: GlobalMetrics = {
  totalClients: 3,
  totalCallsThisMonth: 247,
  totalMRR: 1491,
  avgScore: 81,
}

// ─── Trend data ───────────────────────────────────────────────────────────────

export const trendData: TrendPoint[] = [
  { week: 'S1', closeRate: 57, score: 72 },
  { week: 'S2', closeRate: 60, score: 75 },
  { week: 'S3', closeRate: 62, score: 79 },
  { week: 'S4', closeRate: 65, score: 83 },
  { week: 'S5', closeRate: 64, score: 82 },
  { week: 'S6', closeRate: 68, score: 86 },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

export const TRAINER_ID_TO_KEY: Record<string, keyof import('./types').TrainerScore> = {
  'trainer-marcus': 'marcus',
  'trainer-jamie': 'jamie',
  'trainer-jordan': 'jordan',
  'trainer-taylor': 'taylor',
}

// ─── Rubric (Supabase format) ────────────────────────────────────────────────

export const rubric = {
  id: 'rubric-001',
  name: 'Dog Training Sales Rubric',
  description: 'Rubrica padrão para avaliação de calls de vendas de adestramento',
  is_active: true,
  system_prompt: 'You are an expert sales coach for dog training businesses. Evaluate the call based on the rubric criteria.',
  llm_model: 'openai/gpt-4o-mini',
  created_at: '2026-03-01T10:00:00Z',
}

// ─── Scripts (Supabase format) ───────────────────────────────────────────────

export const scripts = [
  {
    id: 'script-001',
    name: 'Discovery-First Sales Script',
    description: 'Script focado em discovery profundo antes de apresentar a oferta. Baseado nas melhores práticas de Marcus R.',
    rubric_id: 'rubric-001',
    is_active: true,
    created_at: '2026-03-01T12:00:00Z',
    sections: [
      { name: 'Abertura', instructions: 'Cumprimente e estabeleça rapport. Pergunte o motivo do contato.', tips: 'Seja genuíno, não use scripts decorados.' },
      { name: 'Discovery', instructions: 'Faça pelo menos 3 perguntas abertas antes de qualquer apresentação.', tips: 'Identifique a dor real, não o sintoma.' },
      { name: 'Problem Agitation', instructions: 'Aprofunde a dor conectando o problema a impactos emocionais e financeiros.', tips: 'Use perguntas como "e como isso afeta..."' },
      { name: 'Apresentação da Oferta', instructions: 'Conecte a oferta diretamente à dor identificada.', tips: 'Nunca apresente preço antes de estabelecer valor.' },
      { name: 'Fechamento', instructions: 'Proponha o próximo passo com clareza e segurança.', tips: 'Silêncio estratégico após apresentar o preço.' },
    ],
    full_script: 'Script completo de vendas para adestramento de cães...',
    criteria: [
      { name: 'Rapport Building', description: 'Trainer establishes connection in first 2 minutes' },
      { name: 'Open Questions', description: 'At least 3 open questions before presenting offer' },
      { name: 'Pain Identification', description: 'Identifies the real pain, not just the symptom' },
      { name: 'Emotional Connection', description: 'Connects the problem to emotional/financial impact' },
      { name: 'Value Before Price', description: 'Establishes value before revealing pricing' },
      { name: 'Clear Next Steps', description: 'Call ends with a clear commitment or next step' },
    ],
  },
  {
    id: 'script-002',
    name: 'Objection Handling Script',
    description: 'Script focado em técnicas de manejo de objeções de preço e tempo.',
    rubric_id: 'rubric-001',
    is_active: true,
    created_at: '2026-03-05T14:00:00Z',
    sections: [
      { name: 'Identificação da Objeção', instructions: 'Classifique: preço, tempo, autoridade ou necessidade.', tips: 'Nunca responda imediatamente — pause.' },
      { name: 'Reframing', instructions: 'Recontextualize o investimento em termos de custo de inação.', tips: '"Quanto custa NÃO resolver isso?"' },
      { name: 'Prova Social', instructions: 'Use cases específicos de clientes com situação similar.', tips: 'Raça e problema similares funcionam melhor.' },
    ],
    full_script: 'Script de manejo de objeções...',
    criteria: [
      { name: 'Objection Classification', description: 'Correctly identifies type of objection' },
      { name: 'Reframing Technique', description: 'Reframes objection in terms of cost of inaction' },
      { name: 'Social Proof', description: 'Uses relevant case study or testimonial' },
    ],
  },
]

// ─── Calls em formato Supabase (para handlers PostgREST) ────────────────────

export const supabaseCalls = calls.map((call) => ({
  id: call.id,
  rubric_id: 'rubric-001',
  trainer_name: call.trainerName,
  trainer_email: `${call.trainerName.toLowerCase().replace(/\s+/g, '').replace('.', '')}@demo.askmoses.ai`,
  client_name: call.prospect,
  transcript: call.transcript,
  overall_score: call.score,
  total_criteria: 6,
  criteria: [
    { name: 'Discovery', score: call.rubricScores.discovery, feedback: 'Evaluated' },
    { name: 'Problem Agitation', score: call.rubricScores.problemAgitation, feedback: 'Evaluated' },
    { name: 'Offer Presentation', score: call.rubricScores.offerPresentation, feedback: 'Evaluated' },
    { name: 'Objection Handling', score: call.rubricScores.objectionHandling, feedback: 'Evaluated' },
    { name: 'Close & Next Steps', score: call.rubricScores.closeAndNextSteps, feedback: 'Evaluated' },
  ],
  summary: call.feedback,
  strengths: call.strengths,
  improvements: call.improvements,
  call_outcome: call.result === 'closed' ? 'closed' : call.result === 'no-close' ? 'not_closed' : 'partial',
  detected_outcome: call.result,
  email_sent: true,
  email_id: `email-${call.id}`,
  created_at: `${call.date}T10:00:00Z`,
}))
