-- ============================================================
-- 042_fix_users_rls_recursion.sql
-- Conserta recursão infinita detectada no TC-02 (2026-05-13).
--
-- Erro reproduzido em Supabase SQL Editor:
--   ERROR 42P17: infinite recursion detected in policy for relation "users"
--
-- Causa: migration 040 criou a policy `users_select_same_org` com subquery
-- em `memberships`. Memberships tem `memberships_select_by_org` (também
-- 040) que chama `current_org()`. `current_org()` lê users.active_org_id
-- internamente. Postgres detecta o ciclo no parse — mesmo com SECURITY
-- DEFINER em current_org() (que bypassaria RLS em runtime), o planner
-- aborta antes de chegar lá.
--
-- Cycle:
--   users policy → memberships subquery
--   memberships policy → current_org()
--   current_org() body → users + memberships  ← fecha o ciclo
--
-- Fix: dropar `users_select_same_org`. Owner/Trainer listando time já
-- usa createAdminClient (service_role) em todos os caminhos de produção
-- (lib/db/*.ts) — RLS aqui era defense in depth, não funcional. Sem
-- regressão de uso real.
--
-- Trade-off explícito: queries de `users` via supabase client regular
-- (não service_role) só retornam a própria row do user (via
-- `users_select_self`). Se algum endpoint futuro precisar listar users
-- da org via client regular, terá que (a) usar service_role + filtrar
-- por org_id no código, ou (b) introduzir um helper SECURITY DEFINER
-- com BYPASSRLS-eligible owner que faça o join sem o ciclo.
-- ============================================================

DROP POLICY IF EXISTS "users_select_same_org" ON public.users;

-- Sanity: policies restantes em users devem ser
--   - users_service_role_all (FOR ALL via service_role)
--   - users_select_self      (FOR SELECT, id = auth.uid())
-- Sem o select_same_org, qualquer query via authenticated retorna no
-- máximo a própria row do user. Suficiente pro flow normal (login,
-- profile, /api/me) e pra TC-02.
